num_pretraining_steps: 0
online_steps: 100000
env_name: sawyer_press_button
frame_stack: 1
action_repeat: 1
oracle_reset: 1
discount: 0.99
num_init_frames: 1000
eval_every_frames: 10000
num_eval_episodes: 10
save_snapshot: true
replay_buffer_size: 5000000
prior_buffer_size: 200000
replay_buffer_num_workers: 4
nstep: 1
batch_size: 256
seed: 42
device: cuda
save_train_video: true
use_tb: true
lr: 0.0003
feature_dim: ???
use_discrim: true
discrim_type: state
num_discrims: 1
mixup: true
time_step: 1
resets: false
biased_update: 100
rl_pretraining: true
save_buffer: true
q_weights: true
use_demos: true
baseline: 0
alpha: 1
task_encoding: cosine
novelty: 11
agent:
  _target_: SAC.agent
  obs_shape: 46
  action_shape: 4
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.005
  reward_scale_factor: 10.0
  use_tb: ${use_tb}
  hidden_dim: 256
  feature_dim: ${feature_dim}
  from_vision: false
  discrim_hidden_size: 128
discriminator:
  train_interval: 1
  train_steps_per_iteration: 1
  batch_size: 512
  positive_buffer_size: 100000
  negative_buffer_size: 5000000
